apiVersion: v1
kind: Secret
metadata:
  name: jhon-silva-backend-secrets
  namespace: jhon-silva-backend
type: Opaque
data:
  # Base de datos Neon PostgreSQL (Cloud) - Valores en base64
  DB_URL: r2dbc:postgresql://ep-rough-violet-adi6ri0k-pooler.c-2.us-east-1.aws.neon.tech/hackathon?sslmode=require&channel_binding=require
  DB_USERNAME: neondb_owner
  DB_PASSWORD: npg_pHT4NJx3gnSG
  SERVER_PORT: 8080